spring:
  spring:
    cloud:
      aws:
        s3:
          bucket: ${BUCKET_NAME}
        credentials:
          access-key: ${BUCKET_ACCESS}
          secret-key: ${BUCKET_SECRET}
        region:
          static: ap-northeast-2
          auto: false
        stack:
          auto: false
  application:
    name: story
  docker:
    compose:
      file: /absolute/path/to/docker-compose.yml
  datasource:
    url: jdbc:mysql://localhost:3306/story
    username: root
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true

jwt:
  secret: ${JWT_SECRET}

openai:
  api-key: ${AI_KEY}      # 환경 변수로 등록한 내 OpenAI 키
  base-url: https://api.openai.com/v1  # 고정 공식 주소
  timeout-seconds: 60
  models:
    chat: gpt-4o-mini                  # 대화용 (피드백 생성 등)
    embedding: text-embedding-3-small
  options:
    max-tokens: 500
    temperature: 0.8