spring:
  cloud:
     aws:
        s3:
          bucket: ${BUCKET_NAME}
          presigned-url-duration-minutes: 60
        region:
          static: ap-northeast-2
          auto: false
        stack:
          auto: false
  application:
    name: story
  docker:
    compose:
      file: /absolute/path/to/docker-compose.yml
  datasource:
    url: jdbc:mysql://localhost:3306/story
    username: root
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
  task:
    execution:
      pool:
        core-size: 4
        max-size: 8
        queue-capacity: 100

google:
  client-id: ${GOOGLE_ID}
  client-secret: ${GOOGLE_SECRET}
  redirect-uri: ${GOOGLE_URI}
  public-key: ${GOOGLE_KEY}
kakao:
  client-id: ${KAKAO_ID}
  redirect-uri: ${KAKAO_URI}

jwt:
  secret: ${JWT_SECRET}
  expire-time: 60

openai:
  api-key: ${AI_KEY}      # 환경 변수로 등록한 내 OpenAI 키
  base-url: https://api.openai.com/v1  # 고정 공식 주소니다. 중요한 정보는
  timeout-seconds: 60
  models:
    chat: gpt-4o-mini                  # 대화용 (피드백 생성 등)
    embedding: text-embedding-3-small
  options:
    max-tokens: 600
    temperature: 0.8

base:
  url: http://localhost:8080